Feature/development
EvyOliveira/evysLearning pull request #2
Opened 2024-04-16 23:13 UTC by EvyOliveira

## Description
For this delivery, we have project documentation, refactor CRUD functions, database script and markdown for pull requests.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Tests
- [ ] Other

Thank you.

2024-04-16 23:28 UTC, lalizita requested changes
Good job! Just some changes and questions.

2024-04-16 23:28 UTC, lalizita commented on README.md
> +$ git clone git@github.com:EvyOliveira/evysLearning.git
This script is not needed here, because there is more than one way to clone a repo (https and ssh).

Just the option _Clone this repository_ is enough.

2024-04-16 23:28 UTC, lalizita commented on README.md
> +$ git mod init git@github.com:EvyOliveira/evysLearning.git
This script is not needed here too.

When you start your go project, it is configured in your go.mod file (go.mod must be commited with the project)

2024-04-16 23:28 UTC, lalizita commented on README.md
> +$ go mod tidy
It only will be needed if you install some new package in the project

2024-04-16 23:28 UTC, lalizita commented on diagram.png
CONGRAAAATS!!!!! ✨

2024-04-16 23:28 UTC, lalizita commented on script.sql
> +CREATE TABLE "Courses" (
Wich database are you using?
You can test you SQL scripts here

https://www.db-fiddle.com/

2024-04-16 23:30 UTC, EvyOliveira commented on script.sql
> +CREATE TABLE "Courses" (
I´m using PostgreSQL. I will test through this link and submit again for review. Thank you, @lalizita.

2024-04-16 23:31 UTC, EvyOliveira commented on diagram.png
Thank you for all support!

2024-04-16 23:31 UTC, EvyOliveira commented on README.md
> +$ git mod init git@github.com:EvyOliveira/evysLearning.git
You're right. I will remove this part. Thank you!

2024-04-16 23:32 UTC, EvyOliveira commented on README.md
> +$ git clone git@github.com:EvyOliveira/evysLearning.git
Alright.

2024-04-23 19:25 UTC, lalizita approved these changes
Too much good! Congrats for you evolution!

2024-04-23 20:55 UTC, merged